

services:
  ui:
    # local build
    build:
      context: .
      dockerfile: Dockerfile

    # docker hub build
    container_name: streaming-platform-ui
    # image: minhnguyen1489/streaming-platform:ui
    ports:
      - "8084:8084"
    restart: unless-stopped
    # depends_on:
    #   - minio
    environment:
      - NODE_ENV=production

volumes:
  minio_data:
